version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ecrituredesoie_app
        ports:
            - "80:80"
        volumes:
            - ./var:/var/www/html/var
            - ./.env.prod:/var/www/html/.env.local
        environment:
            - APP_ENV=prod
        networks:
            - ecrituredesoie_network
        restart: unless-stopped
        depends_on:
            - db
            - mongodb
